language: ruby
rvm:
  - "1.9.3"
  - "1.8.7"
  - "2.0.0"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

notifications:
  email: false
